---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ratelimit-local
  name: ratelimit-local
  namespace: ratelimit
spec:
  ports:
    - name: http-port
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: grpc-port
      port: 8081
      protocol: TCP
      targetPort: 8081
    - name: http-debug
      port: 6070
      protocol: TCP
      targetPort: 6070
  selector:
    app: ratelimit-local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratelimit-local
  namespace: ratelimit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratelimit-local
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ratelimit-local
    spec:
      containers:
        - command: ["/bin/ratelimit"]
          env:
            - name: GRPC_HOST
              value: "::"
            - name: HOST
              value: "::"
            - name: LOG_LEVEL
              value: trace
            - name: REDIS_SOCKET_TYPE
              value: tcp
            - name: REDIS_URL
              value: redis.ratelimit.svc.cluster.local:6379
            - name: RUNTIME_IGNOREDOTFILES
              value: "true"
            - name: RUNTIME_ROOT
              value: /data
            - name: RUNTIME_SUBDIRECTORY
              value: ratelimit
            - name: RUNTIME_WATCH_ROOT
              value: "false"
            - name: USE_STATSD
              value: "false"
          image: envoyproxy/ratelimit:master
          imagePullPolicy: Always
          name: ratelimit-local
          ports:
            - containerPort: 8080
            - containerPort: 8081
            - containerPort: 6070
          resources:
            limits:
              cpu: 250m
              memory: 128Mi
            requests:
              cpu: 125m
              memory: 64Mi
          volumeMounts:
            - mountPath: /data/ratelimit/config
              name: config-volume
      volumes:
        - configMap:
            name: ratelimit-config
          name: config-volume